### ISSUE TITLE
When clicking Extend on an Expired resource its status should change to "Valid"

### ISSUE THREAD

**Issue by shklar** [shklar/SubMinimizer#10]
@bergano65 
I clicked an expired resource and it remained Expired.
The Expiration date was updated, but the status wasn't. The status should also be updated, and the "Extend" button should become greyed out so that nobody thinks about clicking it again.

**Comment by bergano65** [comment]
if extending resource is valid for not expired resources why to disable extend button

**Comment by shklar** [comment]
I meant that if you have already clicked that button, there is no point in allowing to click it again.
It will also give the user an indication that his click was registered.

Also please note that there are other fields that get updated like the owner name and expiration date

**Comment by bergano65** [comment]
When enable it?

**Comment by shklar** [comment]
The next time the web page is refereshed

**Comment by bergano65** [comment]
ok

**Comment by bergano65** [comment]
Same about reservation button?

From: Evgeny Vitenberg
Sent: Monday, November 7, 2016 9:50 AM
To: 'shklar/SubMinimizer' <reply@reply.github.com>; shklar/SubMinimizer <SubMinimizer@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [shklar/SubMinimizer] When clicking Extend on an Expired resource its status should change to "Valid" (#10)

ok

**Comment by shklar** [comment]
Yep

Sent from my Windows Phone
________________________________

**Comment by bergano65** [comment]
ok
