### ISSUE TITLE
Send daily email only in case there is something interesting to report 

### ISSUE THREAD

**Issue by shklar** [shklar/SubMinimizer#27]
In particular, don't send emails in case there are only valid resources in the subscriptions.

**Comment by bergano65** [comment]
under implementation now. commonly  thinking a I would say it should be flexible configurable. something like report settings per subscription. I suggest to place those settings at settings dialogue separating them from another options by line with text "report options"
- don't report if only valid resources exist ( first check box)
- send mails to coadmins 
...
btw who is coadmins?

**Comment by shklar** [comment]
coadmins is a concept in Azure management. Each subscription has a list of coadmins who have full priveleges

**Comment by shklar** [comment]
adding a separate section for the report is a good idea.

**Comment by bergano65** [comment]
issue remained opened, please add cases of mail configuring

**Comment by shklar** [comment]
What do you mean by "please add cases of mail configuring"?

**Comment by bergano65** [comment]
If somebody has idea how to configure mail report with  another setting this issue comments will be best place )

**Comment by shklar** [comment]
No need to keep an issue open just as a placeholder.
If we have new ideas we will open new issues :)

**Comment by bergano65** [comment]
If somebody else will have such ideas, isn’t convenient he will see opened issue and will get direction to think about extending options?
