### ISSUE TITLE
Allow only the subscription owner to disconnect or change the settings of the subscription

### ISSUE THREAD

**Issue by shklar** [shklar/SubMinimizer#28]
Please make sure to validate that the user is the current owner.
We do not want to allow anyone else to disconnect.

In case this is not the user, let them see the settings, but they should get some error pop up message telling them that they should contact the current owner.

**Comment by bergano65** [comment]
Paid attention if connection failed no message shown. Small issue I think )

**Comment by bergano65** [comment]
I don’t understand procedure yet.
Anybody can connect subscription, right?
If he has access at azure we allow it, right?
At success we store his name at database as property of connected subscription, right?
Database is shared for all application users, right?
If you are connected to this subscription at another machine already but your code somehow retrieves subscription connected by property you get another user name, right?
Why?

**Comment by shklar** [comment]
A better term would be "Register".
Any user that has access to a subscription can register it. Once he has registered nobody else can unregister it (or take it away from him) or change settings. Only he can.
