### ISSUE TITLE
 authentication fails when machine isn't connected to corpnet

### ISSUE THREAD

**Issue by bergano65** [shklar/SubMinimizer#35]
I always get token expired when starting application

**Comment by shklar** [comment]
This is Azure Authentication. It is not related to corpnet.
I would like to understand if any of our user encounter similar difficulties.

**Comment by bergano65** [comment]
Did you try to run application outside of corpnet?

**Comment by bergano65** [comment]
Btw, probably for you will be easier to fix this issue. It’s interesting for me to a understand azure authentication but if issue is actually exist for all or significant amount of users it’s urgent to fix it.

**Comment by shklar** [comment]
No.
I will try it at home today.

**Comment by bergano65** [comment]
Sorry didn’t you succeed?

**Comment by bergano65** [comment]
this happened when application started from visual studio. now not
