### ISSUE TITLE
Allow extending a resource by a different duration than the default

### ISSUE THREAD

**Issue by shklar** [shklar/SubMinimizer#4]
Allow the user to define the expected period upfront up to some maximum limit (defined by the subscription owner)

**Comment by shklar** [comment]
In particular I suggest adding another button called "Reserve" which would extend the resource for a long period of time,
That way the user can either Extend for 30 (default) days or Reserve for 180 (default) days.
Both values should be configurable in the subscription settings.

**Comment by shklar** [comment]
Add a “Reserve” operation for each resource.
It is very much like “Extend”, but it applies to a much longer period of time.  So for instance “Extend” by default will give you 30 days, whereas “Reserve” will give you 180 days.
You should:
•	Add a “Reserve” duration field to the subscription setting
•	Add a “Reserve” button to a resource on the Analyze view
•	Add an Ajax operation that updates the reservation period by the requested period.

Use 30 and 180 days as default for both operation.

**Comment by bergano65** [comment]
done

**Comment by shklar** [comment]
Did you submit a pull request for this issue?

**Comment by shklar** [comment]
Fixed by
  https://github.com/shklar/SubMinimizer/pull/11
